# Generated by Django 5.1.3 on 2024-12-01 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_text_storereview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereview',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
